name: word_game
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.4
  http: ^0.13.3
  flutter_bloc: ^5.0.0
  meta: ^1.1.8
  equatable: ^1.2.0
  google_fonts: ^2.1.0
  # firebase_performance: ^0.7.0+5
  cached_network_image: ^3.0.0-nullsafety
  shimmer_animation: ^2.0.0
  uuid: ^3.0.4
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/avatar/
    - assets/maps/
    - google_fonts/